# Generated by Django 2.2.7 on 2020-05-06 14:41

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200416_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='наименование')),
                ('type', models.CharField(blank=True, choices=[('system', 'системный'), ('family', 'семья'), ('other', 'другое')], db_index=True, max_length=255, null=True, verbose_name='тип')),
                ('integration_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Данные об интеграции')),
            ],
            options={
                'verbose_name': 'Группа профилей',
                'verbose_name_plural': 'Группы профилей',
            },
        ),
        migrations.CreateModel(
            name='ProfileToGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ProfileGroup')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'verbose_name': 'связь профиля с группой',
                'verbose_name_plural': 'связи профилей с группами',
            },
        ),
        migrations.AddField(
            model_name='profilegroup',
            name='profiles',
            field=models.ManyToManyField(related_name='groups', through='profiles.ProfileToGroup', to='profiles.Profile', verbose_name='профили'),
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(blank=True, choices=[('child', 'ребенок'), ('parent', 'родитель'), ('sibling', 'родной брат/сестра'), ('other', 'другое')], max_length=255, null=True, verbose_name='кем приходится зависимый профиль основному')),
                ('can_update_slave_appointments', models.BooleanField(default=False, verbose_name='может основной видеть/изменять назначения зависимого?')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='profiles.Profile', verbose_name='основной профиль')),
                ('slave', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='slave_relations', to='profiles.Profile', verbose_name='зависимый профиль')),
            ],
            options={
                'verbose_name': 'Отношение с другим профилем',
                'verbose_name_plural': 'Отношения с другими профилями',
                'unique_together': {('master', 'slave')},
            },
        ),
    ]
