# Generated by Django 3.1.5 on 2021-01-13 19:51

import apps.core.utils
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200506_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture_draft',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture_original/', validators=[apps.core.utils.validate_image_max_size], verbose_name='фото профиля'),
        ),
        migrations.AlterField(
            model_name='profilegroup',
            name='integration_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Данные об интеграции'),
        ),
    ]
