# Generated by Django 2.2.7 on 2020-01-10 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'fixture_migrations',
            },
        ),
    ]
