# Generated by Django 2.2.3 on 2019-09-12 08:43

import apps.moderation.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'на модерации'), (-10, 'отклонено'), (10, 'одобрено')], db_index=True, default=0, verbose_name='статус')),
                ('moderated_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='дата модерации')),
                ('reason', models.TextField(blank=True, verbose_name='комментарий модератора')),
                ('watched_changes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, verbose_name='изменения')),
                ('section', models.SmallIntegerField(blank=True, choices=[(1, 'модераторы'), (2, 'техподдержка')], db_index=True, null=True, verbose_name='зона ответственности')),
                ('index', models.SmallIntegerField(blank=True, db_index=True, editable=False, null=True)),
                ('changed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='changed_by_set', to=settings.AUTH_USER_MODEL, verbose_name='кем изменен')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('moderated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderated_by_set', to=settings.AUTH_USER_MODEL, verbose_name='модератор')),
            ],
            options={
                'verbose_name': 'запрос на модерацию',
                'verbose_name_plural': 'запросы на модерацию',
                'ordering': ('-created',),
            },
            bases=(apps.moderation.models.PreValidationMixin, models.Model),
        ),
    ]
