# Generated by Django 2.2.3 on 2019-09-12 11:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_auto_20190912_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationrequest',
            name='watched_changes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='изменения'),
        ),
    ]
