# Generated by Django 2.2.7 on 2020-04-28 12:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20200422_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentquestion',
            name='answer',
            field=ckeditor.fields.RichTextField(help_text='', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='frequentquestion',
            name='question',
            field=ckeditor.fields.RichTextField(help_text='', verbose_name='Вопрос'),
        ),
    ]
