# Generated by Django 3.1.7 on 2021-03-13 09:42

import ckeditor.fields
from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20200730_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentquestion',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='frequentquestion',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='created',
            field=model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='frequentquestion',
            name='answer',
            field=ckeditor.fields.RichTextField(help_text='', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='frequentquestion',
            name='question',
            field=ckeditor.fields.RichTextField(help_text='', verbose_name='Вопрос'),
        ),
    ]
