# Generated by Django 2.2.7 on 2020-02-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpoDevice',
        ),
    ]
