# Generated by Django 2.2.3 on 2019-07-24 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Код')),
                ('provider', models.TextField(blank=True, verbose_name='Сотовый оператор')),
                ('digits_number', models.IntegerField(blank=True, null=True, verbose_name='Знаков после кода')),
                ('is_wired', models.BooleanField(db_index=True, default=False, verbose_name='Стационарный?')),
            ],
            options={
                'verbose_name': 'код телефона',
                'verbose_name_plural': 'коды телефонов',
            },
        ),
        migrations.CreateModel(
            name='SMSCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('value', models.CharField(db_index=True, max_length=6)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS-код',
                'verbose_name_plural': 'SMS-коды',
            },
        ),
    ]
