# Generated by Django 2.2.7 on 2020-08-25 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0005_auto_20200825_1237'),
        ('clinics', '0008_auto_20200730_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_displayed', models.BooleanField(default=False, verbose_name='отображается?')),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], db_index=True, verbose_name='оценка')),
                ('text', models.TextField(verbose_name='Текст')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.Appointment', verbose_name='запись на прием')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinics.Doctor', verbose_name='врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinics.Patient', verbose_name='пациент')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
