# Generated by Django 2.2.7 on 2020-11-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20201021_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'новая'), (1, 'на модерации'), (2, 'обработан')], db_index=True, default=0, null=True, verbose_name='статус'),
        ),
    ]
