# Generated by Django 3.1.7 on 2021-05-28 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='patient',
            new_name='author_patient',
        ),
        migrations.AlterField(
            model_name='review',
            name='author_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='clinics.patient', verbose_name='пациент - автор отзыва'),
        ),
    ]
