# Generated by Django 2.2.7 on 2020-04-22 14:04

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslottoappointment',
            old_name='request',
            new_name='appointment',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='integration_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Данные об интеграции'),
        ),
    ]
