# Generated by Django 2.2.7 on 2020-04-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20200422_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.CharField(blank=True, choices=[('patient', 'пациент'), ('doctor', 'доктор'), ('administrator', 'администратор')], max_length=100, null=True, verbose_name='Кем создана запись?'),
        ),
    ]
