# Generated by Django 2.2.7 on 2020-05-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'спрятана'), (1, 'на модерации'), (2, 'отклонена'), (10, 'запланирована'), (20, 'отменен администратором'), (23, 'запрос на отмену от пациента'), (21, 'отменен пациентом'), (22, 'отменен доктором'), (30, 'пациент пришел'), (40, 'на приеме'), (50, 'приём окончен, требуется оплата'), (60, 'прием завершен')], db_index=True, null=True, verbose_name='статус'),
        ),
    ]
