# Generated by Django 3.1.5 on 2021-01-16 21:18

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20200825_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='integration_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Данные об интеграции'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='integration_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Данные об интеграции'),
        ),
    ]
